version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-admin:
    image: rediscommander/redis-commander
    ports:
      - "6380:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379